/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : translation.g
 *     -                            On : 2012-12-03 22:18:38
 *     -                for the parser : translationParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.ListIterator;
import java.util.Stack;

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "translationParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   ptranslationParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  ptranslationParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->ptranslationParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->ptranslationParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */

/* ruleAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declarations for creating a translationParser_entry scope set
 */
static ptranslationParser_entry_SCOPE   ptranslationParser_entryPush(ptranslationParser ctx);
static void ANTLR3_CDECL entryFree(ptranslationParser_entry_SCOPE scope);
/* ----------------------------------------------------------------------------- */


/* ruleAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL entryFree(ptranslationParser_entry_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a translationParser entry scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->ptranslationParser_entryTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( ptranslationParser_entry_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static ptranslationParser_entry_SCOPE
ptranslationParser_entryPush(ptranslationParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    ptranslationParser_entry_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->ptranslationParser_entryStack->size(ctx->ptranslationParser_entryStack) > ctx->ptranslationParser_entryStack_limit)
    {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (ptranslationParser_entry_SCOPE)ctx->ptranslationParser_entryStack->get(ctx->ptranslationParser_entryStack, ctx->ptranslationParser_entryStack_limit);
    }
    else
    {
        // Need a new allocation
        //
        newAttributes = (ptranslationParser_entry_SCOPE) ANTLR3_MALLOC(sizeof(translationParser_entry_SCOPE));
        if  (newAttributes != NULL)
        {
            /* Standard ANTLR3 library implementation
             */
            ctx->ptranslationParser_entryStack->push(ctx->ptranslationParser_entryStack, newAttributes, (void (*)(void *))entryFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->ptranslationParser_entryStack_limit++;

	/* Return value is the pointer to the new entry, which may be used locally
	 * without de-referencing via the context.
     */
    return  newAttributes;
}







/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   translationParserTokenNames[11+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "LBRACK",
        (pANTLR3_UINT8) "LCURLY",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "NUM",
        (pANTLR3_UINT8) "RBRACK",
        (pANTLR3_UINT8) "RCURLY",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "VERSION",
        (pANTLR3_UINT8) "WHITE"
       };


/* ruleAttributeScopeFuncMacro(scope)
 */
/** Function for popping the top value from a ptranslationParser_entryStack
 */
void
ptranslationParser_entryPop(ptranslationParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
	// If the user supplied the scope entries with a free function,then call it first
	//
    if	(SCOPE_TOP(entry)->free != NULL)
	{
        SCOPE_TOP(entry)->free(SCOPE_TOP(entry));
	}

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->ptranslationParser_entryStack_limit--;
    SCOPE_TOP(entry) = (ptranslationParser_entry_SCOPE)(ctx->ptranslationParser_entryStack->get(ctx->ptranslationParser_entryStack, ctx->ptranslationParser_entryStack_limit - 1));
}



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	top    (ptranslationParser ctx, SS_translationset tset);
static 
 void
	header    (ptranslationParser ctx, SS_translationset tset);
static 
 void
	entry    (ptranslationParser ctx, SS_translationset tset);
static 
 void
	entry_list    (ptranslationParser ctx, SS_translationset tset, SS_translation trans);
static 
 SS_translationset
	file    (ptranslationParser ctx, ArrayList<SS_log> loglist);
static void	translationParserFree(ptranslationParser ctx);
static void     translationParserReset (ptranslationParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "translation.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new translationParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API ptranslationParser
translationParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return translationParserNewSSD(instream, NULL);
}

/** \brief Create a new translationParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API ptranslationParser
translationParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    ptranslationParser ctx;	    /* Context structure we will build and return   */

    ctx	= (ptranslationParser) ANTLR3_CALLOC(1, sizeof(translationParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in translationParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our translationParser interface
     */
    ctx->top	= top;
    ctx->header	= header;
    ctx->entry	= entry;
    ctx->entry_list	= entry_list;
    ctx->file	= file;
    ctx->free			= translationParserFree;
    ctx->reset			= translationParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* ruleAttributeScope(scope)
     */
    ctx->ptranslationParser_entryPush     = ptranslationParser_entryPush;
    ctx->ptranslationParser_entryStack    = antlr3StackNew(0);
    ctx->ptranslationParser_entryStack_limit    = 0;
    ctx->ptranslationParser_entryTop      = NULL;




    /* Install the token table
     */
    PSRSTATE->tokenNames   = translationParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
translationParserReset (ptranslationParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 translationParserFree(ptranslationParser ctx)
 {
    /* Free any scope memory
     */
    /* ruleAttributeScope(scope)
     */
    ctx->ptranslationParser_entryStack->free(ctx->ptranslationParser_entryStack);



	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return translationParserTokenNames;
}




/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_top172  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_top172_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_top172	= { FOLLOW_WHITE_in_top172_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VERSION_in_top177  */
static	ANTLR3_BITWORD FOLLOW_VERSION_in_top177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004010) };
static  ANTLR3_BITSET_LIST FOLLOW_VERSION_in_top177	= { FOLLOW_VERSION_in_top177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_top179  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_top179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_top179	= { FOLLOW_WHITE_in_top179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COLON_in_top185  */
static	ANTLR3_BITWORD FOLLOW_COLON_in_top185_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000005000) };
static  ANTLR3_BITSET_LIST FOLLOW_COLON_in_top185	= { FOLLOW_COLON_in_top185_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_top187  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_top187_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_top187	= { FOLLOW_WHITE_in_top187_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_top192  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_top192_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004120) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_top192	= { FOLLOW_STRING_in_top192_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_top201  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_top201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000120) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_top201	= { FOLLOW_WHITE_in_top201_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_top204  */
static	ANTLR3_BITWORD FOLLOW_set_in_top204_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_top204	= { FOLLOW_set_in_top204_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBRACK_in_header236  */
static	ANTLR3_BITWORD FOLLOW_LBRACK_in_header236_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_LBRACK_in_header236	= { FOLLOW_LBRACK_in_header236_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_header240  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_header240_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_header240	= { FOLLOW_STRING_in_header240_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBRACK_in_header242  */
static	ANTLR3_BITWORD FOLLOW_RBRACK_in_header242_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBRACK_in_header242	= { FOLLOW_RBRACK_in_header242_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_entry271  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_entry271_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_entry271	= { FOLLOW_WHITE_in_entry271_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_header_in_entry274  */
static	ANTLR3_BITWORD FOLLOW_header_in_entry274_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004120) };
static  ANTLR3_BITSET_LIST FOLLOW_header_in_entry274	= { FOLLOW_header_in_entry274_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_entry278  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_entry278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000120) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_entry278	= { FOLLOW_WHITE_in_entry278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_entry281  */
static	ANTLR3_BITWORD FOLLOW_set_in_entry281_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000051A2) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_entry281	= { FOLLOW_set_in_entry281_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_entry_list_in_entry290  */
static	ANTLR3_BITWORD FOLLOW_entry_list_in_entry290_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000051A2) };
static  ANTLR3_BITSET_LIST FOLLOW_entry_list_in_entry290	= { FOLLOW_entry_list_in_entry290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_entry_list316  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_entry_list316_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_entry_list316	= { FOLLOW_WHITE_in_entry_list316_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LCURLY_in_entry_list319  */
static	ANTLR3_BITWORD FOLLOW_LCURLY_in_entry_list319_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_LCURLY_in_entry_list319	= { FOLLOW_LCURLY_in_entry_list319_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUM_in_entry_list323  */
static	ANTLR3_BITWORD FOLLOW_NUM_in_entry_list323_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_NUM_in_entry_list323	= { FOLLOW_NUM_in_entry_list323_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RCURLY_in_entry_list325  */
static	ANTLR3_BITWORD FOLLOW_RCURLY_in_entry_list325_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000005000) };
static  ANTLR3_BITSET_LIST FOLLOW_RCURLY_in_entry_list325	= { FOLLOW_RCURLY_in_entry_list325_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_entry_list331  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_entry_list331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_entry_list331	= { FOLLOW_WHITE_in_entry_list331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_entry_list336  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_entry_list336_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004120) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_entry_list336	= { FOLLOW_STRING_in_entry_list336_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITE_in_entry_list344  */
static	ANTLR3_BITWORD FOLLOW_WHITE_in_entry_list344_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000120) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITE_in_entry_list344	= { FOLLOW_WHITE_in_entry_list344_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_entry_list347  */
static	ANTLR3_BITWORD FOLLOW_set_in_entry_list347_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_entry_list347	= { FOLLOW_set_in_entry_list347_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_top_in_file382  */
static	ANTLR3_BITWORD FOLLOW_top_in_file382_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000006162) };
static  ANTLR3_BITSET_LIST FOLLOW_top_in_file382	= { FOLLOW_top_in_file382_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_entry_in_file387  */
static	ANTLR3_BITWORD FOLLOW_entry_in_file387_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004042) };
static  ANTLR3_BITSET_LIST FOLLOW_entry_in_file387	= { FOLLOW_entry_in_file387_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start top
 * translation.g:31:1: top[SS_translationset tset] : ( ( WHITE )? kw= VERSION ( WHITE )? COLON ( WHITE )? str= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) ) ;
 */
static void
top(ptranslationParser ctx, SS_translationset tset)
{
    pANTLR3_COMMON_TOKEN    kw;
    pANTLR3_COMMON_TOKEN    str;

    /* Initialize rule variables
     */

    kw       = NULL;
    str       = NULL;

    {
        // translation.g:32:12: ( ( ( WHITE )? kw= VERSION ( WHITE )? COLON ( WHITE )? str= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) ) )
        // translation.g:32:14: ( ( WHITE )? kw= VERSION ( WHITE )? COLON ( WHITE )? str= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) )
        {
            // translation.g:32:14: ( ( WHITE )? kw= VERSION ( WHITE )? COLON ( WHITE )? str= STRING )?
            {
                int alt4=2;
                switch ( LA(1) )
                {
                    case WHITE:
                    	{
                    		switch ( LA(2) )
                    		{
                    		    case VERSION:
                    		    	{
                    		    		alt4=1;
                    		    	}
                    		        break;
                    		}

                    	}
                        break;
                    case VERSION:
                    	{
                    		alt4=1;
                    	}
                        break;
                }

                switch (alt4)
                {
            	case 1:
            	    // translation.g:32:15: ( WHITE )? kw= VERSION ( WHITE )? COLON ( WHITE )? str= STRING
            	    {
            	        // translation.g:32:15: ( WHITE )?
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	                case WHITE:
            	                	{
            	                		alt1=1;
            	                	}
            	                    break;
            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // translation.g:32:15: WHITE
            	        	    {
            	        	         MATCHT(WHITE, &FOLLOW_WHITE_in_top172);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruletopEx;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	        kw = (pANTLR3_COMMON_TOKEN) MATCHT(VERSION, &FOLLOW_VERSION_in_top177);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletopEx;
            	        }


            	        // translation.g:32:33: ( WHITE )?
            	        {
            	            int alt2=2;
            	            switch ( LA(1) )
            	            {
            	                case WHITE:
            	                	{
            	                		alt2=1;
            	                	}
            	                    break;
            	            }

            	            switch (alt2)
            	            {
            	        	case 1:
            	        	    // translation.g:32:33: WHITE
            	        	    {
            	        	         MATCHT(WHITE, &FOLLOW_WHITE_in_top179);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruletopEx;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	        {

            	            	if (tset.version != null)
            	            	{
            	            		System.out.print("Hey! the version was previously defined. The definition at line "+(kw->getLine(kw))+" will be ignored!\n");
            	            		SS_log log1 = new SS_log((kw->getLine(kw)), (kw->getCharPositionInLine(kw)), "Re-Definition", "The version was previously defined as "+ tset.version + ", so this declaration will be ignored");
            	            		tset.loglist.add(log1);
            	            	}

            	        }


            	         MATCHT(COLON, &FOLLOW_COLON_in_top185);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletopEx;
            	        }


            	        // translation.g:40:9: ( WHITE )?
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	                case WHITE:
            	                	{
            	                		alt3=1;
            	                	}
            	                    break;
            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // translation.g:40:9: WHITE
            	        	    {
            	        	         MATCHT(WHITE, &FOLLOW_WHITE_in_top187);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruletopEx;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	        str = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_top192);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletopEx;
            	        }


            	        {

            	            	tset.version = new String((str->getText(str)));

            	        }


            	    }
            	    break;

                }
            }

            // translation.g:43:6: ( ( WHITE )? ( COMMENT | NEWLINE ) )
            // translation.g:43:7: ( WHITE )? ( COMMENT | NEWLINE )
            {
                // translation.g:43:7: ( WHITE )?
                {
                    int alt5=2;
                    switch ( LA(1) )
                    {
                        case WHITE:
                        	{
                        		alt5=1;
                        	}
                            break;
                    }

                    switch (alt5)
                    {
                	case 1:
                	    // translation.g:43:7: WHITE
                	    {
                	         MATCHT(WHITE, &FOLLOW_WHITE_in_top201);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruletopEx;
                	        }


                	    }
                	    break;

                    }
                }

                if ( LA(1) == COMMENT || LA(1) == NEWLINE )
                {
                    CONSUME();
                    PERRORRECOVERY=ANTLR3_FALSE;
                }
                else
                {
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                    EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                    EXCEPTION->expectingSet = NULL;

                    goto ruletopEx;
                }


            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletopEx; /* Prevent compiler warnings */
    ruletopEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end top */

/**
 * $ANTLR start header
 * translation.g:46:1: header[SS_translationset tset] : LBRACK str= STRING RBRACK ;
 */
static void
header(ptranslationParser ctx, SS_translationset tset)
{
    pANTLR3_COMMON_TOKEN    str;

    /* Initialize rule variables
     */

    str       = NULL;

    {
        // translation.g:47:8: ( LBRACK str= STRING RBRACK )
        // translation.g:47:10: LBRACK str= STRING RBRACK
        {
             MATCHT(LBRACK, &FOLLOW_LBRACK_in_header236);
            if  (HASEXCEPTION())
            {
                goto ruleheaderEx;
            }


            str = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_header240);
            if  (HASEXCEPTION())
            {
                goto ruleheaderEx;
            }


             MATCHT(RBRACK, &FOLLOW_RBRACK_in_header242);
            if  (HASEXCEPTION())
            {
                goto ruleheaderEx;
            }


            {
                 
                  String x4 = new String((str->getText(str)).substring(1,(str->getText(str)).length()-1)); 
                  SS_translation y4;
                  try 
                  {
                     y4 = tset.by_format.get(x4);
                  }
                  catch (IndexOutOfBoundsException excpt)
                  {
                     y4 = null;
                  }
                  if (y4 != null)
                  {
                	System.out.print("Hey-- the header string at line "+(str->getLine(str))+" has already been declared at line "+y4.lineno+"!!!\n");
                	SS_log log1 = new SS_log((str->getLine(str)), (str->getCharPositionInLine(str)), "Re-Definition", "The header name "+x4+" was previously defined at line "+ y4.lineno + ", so this declaration will be ignored");
                	tset.loglist.add(log1);
                  }
                  else
                  {
                	(SCOPE_TOP(entry))->hdr= new SS_translation(); 
                  	(SCOPE_TOP(entry))->hdr.lineno = (str->getLine(str)); 
                  	(SCOPE_TOP(entry))->hdr.Format = new String((str->getText(str))); 
                  	(SCOPE_TOP(entry))->hdr.Translations= new ArrayList<SS_translationstring>(); 
                	tset.by_format.put(x4, (SCOPE_TOP(entry))->hdr);
                  }

            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleheaderEx; /* Prevent compiler warnings */
    ruleheaderEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end header */

/**
 * $ANTLR start entry
 * translation.g:75:1: entry[SS_translationset tset] : ( WHITE )? header[tset] ( ( WHITE )? ( COMMENT | NEWLINE ) ) ( entry_list[tset,$entry::hdr] )* ;
 */
static void
entry(ptranslationParser ctx, SS_translationset tset)
{
    /* Initialize rule variables
     */
    ctx->ptranslationParser_entryTop = ptranslationParser_entryPush(ctx);
    {
        // translation.g:79:8: ( ( WHITE )? header[tset] ( ( WHITE )? ( COMMENT | NEWLINE ) ) ( entry_list[tset,$entry::hdr] )* )
        // translation.g:79:10: ( WHITE )? header[tset] ( ( WHITE )? ( COMMENT | NEWLINE ) ) ( entry_list[tset,$entry::hdr] )*
        {
            // translation.g:79:10: ( WHITE )?
            {
                int alt6=2;
                switch ( LA(1) )
                {
                    case WHITE:
                    	{
                    		alt6=1;
                    	}
                        break;
                }

                switch (alt6)
                {
            	case 1:
            	    // translation.g:79:10: WHITE
            	    {
            	         MATCHT(WHITE, &FOLLOW_WHITE_in_entry271);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleentryEx;
            	        }


            	    }
            	    break;

                }
            }

            FOLLOWPUSH(FOLLOW_header_in_entry274);
            header(ctx, tset);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleentryEx;
            }


            // translation.g:79:30: ( ( WHITE )? ( COMMENT | NEWLINE ) )
            // translation.g:79:31: ( WHITE )? ( COMMENT | NEWLINE )
            {
                // translation.g:79:31: ( WHITE )?
                {
                    int alt7=2;
                    switch ( LA(1) )
                    {
                        case WHITE:
                        	{
                        		alt7=1;
                        	}
                            break;
                    }

                    switch (alt7)
                    {
                	case 1:
                	    // translation.g:79:31: WHITE
                	    {
                	         MATCHT(WHITE, &FOLLOW_WHITE_in_entry278);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleentryEx;
                	        }


                	    }
                	    break;

                    }
                }

                if ( LA(1) == COMMENT || LA(1) == NEWLINE )
                {
                    CONSUME();
                    PERRORRECOVERY=ANTLR3_FALSE;
                }
                else
                {
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                    EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                    EXCEPTION->expectingSet = NULL;

                    goto ruleentryEx;
                }


            }


            // translation.g:79:59: ( entry_list[tset,$entry::hdr] )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case WHITE:
                	{
                		switch ( LA(2) )
                		{
                		case COMMENT:
                		case LCURLY:
                		case NEWLINE:
                		case STRING:
                			{
                				alt8=1;
                			}
                		    break;

                		}

                	}
                    break;
                case COMMENT:
                case LCURLY:
                case NEWLINE:
                case STRING:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // translation.g:79:59: entry_list[tset,$entry::hdr]
            	    {
            	        FOLLOWPUSH(FOLLOW_entry_list_in_entry290);
            	        entry_list(ctx, tset, (SCOPE_TOP(entry))->hdr);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleentryEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleentryEx; /* Prevent compiler warnings */
    ruleentryEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    ptranslationParser_entryPop(ctx);

    return ;
}
/* $ANTLR end entry */

/**
 * $ANTLR start entry_list
 * translation.g:82:1: entry_list[SS_translationset tset, SS_translation trans] : ( ( ( WHITE )? LCURLY x= NUM RCURLY )? ( WHITE )? s2= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) ) ;
 */
static void
entry_list(ptranslationParser ctx, SS_translationset tset, SS_translation trans)
{
    pANTLR3_COMMON_TOKEN    x;
    pANTLR3_COMMON_TOKEN    s2;

    /* Initialize rule variables
     */


    	int index1 = -1;

    x       = NULL;
    s2       = NULL;

    {
        // translation.g:87:3: ( ( ( ( WHITE )? LCURLY x= NUM RCURLY )? ( WHITE )? s2= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) ) )
        // translation.g:87:5: ( ( ( WHITE )? LCURLY x= NUM RCURLY )? ( WHITE )? s2= STRING )? ( ( WHITE )? ( COMMENT | NEWLINE ) )
        {
            // translation.g:87:5: ( ( ( WHITE )? LCURLY x= NUM RCURLY )? ( WHITE )? s2= STRING )?
            {
                int alt12=2;
                switch ( LA(1) )
                {
                    case WHITE:
                    	{
                    		switch ( LA(2) )
                    		{
                    		    case LCURLY:
                    		    case STRING:
                    		    	{
                    		    		alt12=1;
                    		    	}
                    		        break;
                    		}

                    	}
                        break;
                    case LCURLY:
                    case STRING:
                    	{
                    		alt12=1;
                    	}
                        break;
                }

                switch (alt12)
                {
            	case 1:
            	    // translation.g:87:6: ( ( WHITE )? LCURLY x= NUM RCURLY )? ( WHITE )? s2= STRING
            	    {
            	        // translation.g:87:6: ( ( WHITE )? LCURLY x= NUM RCURLY )?
            	        {
            	            int alt10=2;
            	            switch ( LA(1) )
            	            {
            	                case WHITE:
            	                	{
            	                		switch ( LA(2) )
            	                		{
            	                		    case LCURLY:
            	                		    	{
            	                		    		alt10=1;
            	                		    	}
            	                		        break;
            	                		}

            	                	}
            	                    break;
            	                case LCURLY:
            	                	{
            	                		alt10=1;
            	                	}
            	                    break;
            	            }

            	            switch (alt10)
            	            {
            	        	case 1:
            	        	    // translation.g:87:8: ( WHITE )? LCURLY x= NUM RCURLY
            	        	    {
            	        	        // translation.g:87:8: ( WHITE )?
            	        	        {
            	        	            int alt9=2;
            	        	            switch ( LA(1) )
            	        	            {
            	        	                case WHITE:
            	        	                	{
            	        	                		alt9=1;
            	        	                	}
            	        	                    break;
            	        	            }

            	        	            switch (alt9)
            	        	            {
            	        	        	case 1:
            	        	        	    // translation.g:87:8: WHITE
            	        	        	    {
            	        	        	         MATCHT(WHITE, &FOLLOW_WHITE_in_entry_list316);
            	        	        	        if  (HASEXCEPTION())
            	        	        	        {
            	        	        	            goto ruleentry_listEx;
            	        	        	        }


            	        	        	    }
            	        	        	    break;

            	        	            }
            	        	        }

            	        	         MATCHT(LCURLY, &FOLLOW_LCURLY_in_entry_list319);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleentry_listEx;
            	        	        }


            	        	        x = (pANTLR3_COMMON_TOKEN) MATCHT(NUM, &FOLLOW_NUM_in_entry_list323);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleentry_listEx;
            	        	        }


            	        	         MATCHT(RCURLY, &FOLLOW_RCURLY_in_entry_list325);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleentry_listEx;
            	        	        }


            	        	        {
            	        	            index1 = Integer.parseInt((x->getText(x)));
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	        // translation.g:87:75: ( WHITE )?
            	        {
            	            int alt11=2;
            	            switch ( LA(1) )
            	            {
            	                case WHITE:
            	                	{
            	                		alt11=1;
            	                	}
            	                    break;
            	            }

            	            switch (alt11)
            	            {
            	        	case 1:
            	        	    // translation.g:87:75: WHITE
            	        	    {
            	        	         MATCHT(WHITE, &FOLLOW_WHITE_in_entry_list331);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleentry_listEx;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	        s2 = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_entry_list336);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleentry_listEx;
            	        }


            	        {

            	            	if (index1 == -1) index1 = 0;
            	                    boolean prob = false;
            	            	for (SS_translationstring w3 : trans.Translations)
            	                    {
            	                	   if (w3.num == index1)
            	            	   {
            	            		System.out.print("Hey! the translation for "+ trans.Format 
            	            			+" was already defined at line "+ w3.lineno+ ". The string on line "
            	            			+(s2->getLine(s2))+" will be ignored!\n");
            	            		SS_log log1 = new SS_log((s2->getLine(s2)), (s2->getCharPositionInLine(s2)), "Re-Definition", "The translation for '"+ trans.Format + "' was already defined at line "+ w3.lineno+", so this declaration will be ignored");
            	            		tset.loglist.add(log1);
            	            		prob = true;
            	            	   }
            	                    }
            	            	if (!prob)
            	            	{
            	            		String z4 = new String((s2->getText(s2)).substring(1,(s2->getText(s2)).length()-1));
            	            		SS_translationstring z2 = new SS_translationstring(z4);
            	            		z2.lineno = (s2->getLine(s2));
            	                            z2.num = index1;
            	            		/* System.out.println("== About to set Translations[" + index1 + "] to: " + z2); */
            	            		trans.Translations.add(z2);
            	            	}

            	        }


            	    }
            	    break;

                }
            }

            // translation.g:112:5: ( ( WHITE )? ( COMMENT | NEWLINE ) )
            // translation.g:112:6: ( WHITE )? ( COMMENT | NEWLINE )
            {
                // translation.g:112:6: ( WHITE )?
                {
                    int alt13=2;
                    switch ( LA(1) )
                    {
                        case WHITE:
                        	{
                        		alt13=1;
                        	}
                            break;
                    }

                    switch (alt13)
                    {
                	case 1:
                	    // translation.g:112:6: WHITE
                	    {
                	         MATCHT(WHITE, &FOLLOW_WHITE_in_entry_list344);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleentry_listEx;
                	        }


                	    }
                	    break;

                    }
                }

                if ( LA(1) == COMMENT || LA(1) == NEWLINE )
                {
                    CONSUME();
                    PERRORRECOVERY=ANTLR3_FALSE;
                }
                else
                {
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                    EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                    EXCEPTION->expectingSet = NULL;

                    goto ruleentry_listEx;
                }


            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleentry_listEx; /* Prevent compiler warnings */
    ruleentry_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end entry_list */

/**
 * $ANTLR start file
 * translation.g:115:1: file[ArrayList<SS_log> loglist] returns [SS_translationset transet] : ( top[transet] )* ( entry[transet] )* ;
 */
static SS_translationset
file(ptranslationParser ctx, ArrayList<SS_log> loglist)
{
    SS_translationset transet;


    /* Initialize rule variables
     */


    	  transet= new SS_translationset(loglist);


    {
        // translation.g:120:8: ( ( top[transet] )* ( entry[transet] )* )
        // translation.g:120:10: ( top[transet] )* ( entry[transet] )*
        {
            // translation.g:120:10: ( top[transet] )*

            for (;;)
            {
                int alt14=2;
                switch ( LA(1) )
                {
                case WHITE:
                	{
                		switch ( LA(2) )
                		{
                		case COMMENT:
                		case NEWLINE:
                		case VERSION:
                			{
                				alt14=1;
                			}
                		    break;

                		}

                	}
                    break;
                case COMMENT:
                case NEWLINE:
                case VERSION:
                	{
                		alt14=1;
                	}
                    break;

                }

                switch (alt14)
                {
            	case 1:
            	    // translation.g:120:10: top[transet]
            	    {
            	        FOLLOWPUSH(FOLLOW_top_in_file382);
            	        top(ctx, transet);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefileEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop14;	/* break out of the loop */
            	    break;
                }
            }
            loop14: ; /* Jump out to here if this rule does not match */


            // translation.g:120:24: ( entry[transet] )*

            for (;;)
            {
                int alt15=2;
                switch ( LA(1) )
                {
                case LBRACK:
                case WHITE:
                	{
                		alt15=1;
                	}
                    break;

                }

                switch (alt15)
                {
            	case 1:
            	    // translation.g:120:25: entry[transet]
            	    {
            	        FOLLOWPUSH(FOLLOW_entry_in_file387);
            	        entry(ctx, transet);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefileEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop15;	/* break out of the loop */
            	    break;
                }
            }
            loop15: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefileEx; /* Prevent compiler warnings */
    rulefileEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return transet;
}
/* $ANTLR end file */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
