/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : translation.g
 *     -                            On : 2012-12-03 22:18:39
 *     -                 for the lexer : translationLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "translationLexer.h"
/* ----------------------------------------- */


/** String literals used by translationLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x76, 0x65, 0x72, 0x73, 0x69, 0x6F, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3B, 0x3B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x5C, 0x22,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   ptranslationLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  ptranslationLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->ptranslationLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->ptranslationLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mLBRACK    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mRBRACK    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mLCURLY    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mRCURLY    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mCOLON    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mVERSION    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mNUM    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mNEWLINE    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mWHITE    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMENT    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING    (ptranslationLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (ptranslationLexer ctx);
static void	translationLexerFree(ptranslationLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
translationLexerFree  (ptranslationLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
translationLexerReset (ptranslationLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "translation.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called translationLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success ptranslationLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API ptranslationLexer translationLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return translationLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called translationLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success ptranslationLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API ptranslationLexer translationLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    ptranslationLexer ctx; // Context structure we will build and return

    ctx = (ptranslationLexer) ANTLR3_CALLOC(1, sizeof(translationLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in translationLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our translationLexer interface
     */
    ctx->mLBRACK	= mLBRACK;
    ctx->mRBRACK	= mRBRACK;
    ctx->mLCURLY	= mLCURLY;
    ctx->mRCURLY	= mRCURLY;
    ctx->mCOLON	= mCOLON;
    ctx->mVERSION	= mVERSION;
    ctx->mNUM	= mNUM;
    ctx->mNEWLINE	= mNEWLINE;
    ctx->mWHITE	= mWHITE;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mSTRING	= mSTRING;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= translationLexerFree;
    ctx->reset          = translationLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 16:8: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LBRACK
 *
 * Looks to match the characters the constitute the token LBRACK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLBRACK(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LBRACK;


    // translation.g:16:8: ( '[' )
    // translation.g:16:10: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleLBRACKEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLBRACKEx; /* Prevent compiler warnings */
    ruleLBRACKEx: ;

}
// $ANTLR end LBRACK

//   Comes from: 17:8: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RBRACK
 *
 * Looks to match the characters the constitute the token RBRACK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRBRACK(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RBRACK;


    // translation.g:17:8: ( ']' )
    // translation.g:17:10: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleRBRACKEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRBRACKEx; /* Prevent compiler warnings */
    ruleRBRACKEx: ;

}
// $ANTLR end RBRACK

//   Comes from: 18:8: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LCURLY
 *
 * Looks to match the characters the constitute the token LCURLY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLCURLY(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LCURLY;


    // translation.g:18:8: ( '{' )
    // translation.g:18:10: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleLCURLYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLCURLYEx; /* Prevent compiler warnings */
    ruleLCURLYEx: ;

}
// $ANTLR end LCURLY

//   Comes from: 19:8: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RCURLY
 *
 * Looks to match the characters the constitute the token RCURLY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRCURLY(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RCURLY;


    // translation.g:19:8: ( '}' )
    // translation.g:19:10: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleRCURLYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRCURLYEx; /* Prevent compiler warnings */
    ruleRCURLYEx: ;

}
// $ANTLR end RCURLY

//   Comes from: 20:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COLON;


    // translation.g:20:7: ( ':' )
    // translation.g:20:9: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 22:9: ( 'version' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VERSION
 *
 * Looks to match the characters the constitute the token VERSION
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVERSION(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VERSION;


    // translation.g:22:9: ( 'version' )
    // translation.g:22:11: 'version'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleVERSIONEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVERSIONEx; /* Prevent compiler warnings */
    ruleVERSIONEx: ;

}
// $ANTLR end VERSION

//   Comes from: 25:5: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NUM
 *
 * Looks to match the characters the constitute the token NUM
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNUM(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NUM;


    // translation.g:25:5: ( ( '0' .. '9' )+ )
    // translation.g:25:7: ( '0' .. '9' )+
    {
        // translation.g:25:7: ( '0' .. '9' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // translation.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleNUMEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleNUMEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNUMEx; /* Prevent compiler warnings */
    ruleNUMEx: ;

}
// $ANTLR end NUM

//   Comes from: 26:9: ( ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEWLINE
 *
 * Looks to match the characters the constitute the token NEWLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEWLINE(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEWLINE;


    // translation.g:26:9: ( ( '\\r' )? '\\n' )
    // translation.g:26:11: ( '\\r' )? '\\n'
    {
        // translation.g:26:11: ( '\\r' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '\r':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // translation.g:26:11: '\\r'
        	    {
        	        MATCHC('\r');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\n');
        if  (HASEXCEPTION())
        {
            goto ruleNEWLINEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEWLINEEx; /* Prevent compiler warnings */
    ruleNEWLINEEx: ;

}
// $ANTLR end NEWLINE

//   Comes from: 27:7: ( ( ' ' | '\\t' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITE
 *
 * Looks to match the characters the constitute the token WHITE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHITE(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHITE;


    // translation.g:27:7: ( ( ' ' | '\\t' )+ )
    // translation.g:27:9: ( ' ' | '\\t' )+
    {
        // translation.g:27:9: ( ' ' | '\\t' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case ' ':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // translation.g:
        	        {
        	            if ( LA(1) == '\t' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWHITEEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWHITEEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWHITEEx; /* Prevent compiler warnings */
    ruleWHITEEx: ;

}
// $ANTLR end WHITE

//   Comes from: 28:9: ( ';;' ( . )* NEWLINE )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMENT;


    // translation.g:28:9: ( ';;' ( . )* NEWLINE )
    // translation.g:28:11: ';;' ( . )* NEWLINE
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }




        // translation.g:28:15: ( . )*

        for (;;)
        {
            int alt4=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (LA4_0 == '\r'))
                {
                    alt4=2;
                }
                else if ( (LA4_0 == '\n'))
                {
                    alt4=2;
                }
                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '\t')) || ((LA4_0 >= 0x000B) && (LA4_0 <= '\f')) || ((LA4_0 >= 0x000E) && (LA4_0 <= 0xFFFF))))
                {
                    alt4=1;
                }

            }
            switch (alt4)
            {
        	case 1:
        	    // translation.g:28:15: .
        	    {
        	        MATCHANY();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


        /* 28:11: ';;' ( . )* NEWLINE */
        mNEWLINE(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }



    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 29:8: ( '\"' (~ ( '\\r' | '\\n' | '\"' ) | '\\\\\"' )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(ptranslationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING;


    // translation.g:29:8: ( '\"' (~ ( '\\r' | '\\n' | '\"' ) | '\\\\\"' )* '\"' )
    // translation.g:29:10: '\"' (~ ( '\\r' | '\\n' | '\"' ) | '\\\\\"' )* '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


        // translation.g:29:14: (~ ( '\\r' | '\\n' | '\"' ) | '\\\\\"' )*

        for (;;)
        {
            int alt5=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA5_0 = LA(1);
                if ( (LA5_0 == '\\'))
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA5_2 = LA(2);
                        if ( (LA5_2 == '"'))
                        {
                            {
                               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                                */
                                int LA5_4 = LA(3);
                                if ( (((LA5_4 >= 0x0000) && (LA5_4 <= '\t')) || ((LA5_4 >= 0x000B) && (LA5_4 <= '\f')) || ((LA5_4 >= 0x000E) && (LA5_4 <= 0xFFFF))))
                                {
                                    alt5=2;
                                }

                                else
                                {
                            	alt5=1;
                                }

                            }
                        }
                        else if ( (((LA5_2 >= 0x0000) && (LA5_2 <= '\t')) || ((LA5_2 >= 0x000B) && (LA5_2 <= '\f')) || ((LA5_2 >= 0x000E) && (LA5_2 <= '!')) || ((LA5_2 >= '#') && (LA5_2 <= 0xFFFF))))
                        {
                            alt5=1;
                        }

                    }
                }
                else if ( (((LA5_0 >= 0x0000) && (LA5_0 <= '\t')) || ((LA5_0 >= 0x000B) && (LA5_0 <= '\f')) || ((LA5_0 >= 0x000E) && (LA5_0 <= '!')) || ((LA5_0 >= '#') && (LA5_0 <= '[')) || ((LA5_0 >= ']') && (LA5_0 <= 0xFFFF))))
                {
                    alt5=1;
                }

            }
            switch (alt5)
            {
        	case 1:
        	    // translation.g:29:16: ~ ( '\\r' | '\\n' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRINGEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // translation.g:29:40: '\\\\\"'
        	    {
        	        MATCHS(lit_3);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRINGEx;
        	        }




        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(ptranslationLexer ctx)
{
    {
        //  translation.g:1:8: ( LBRACK | RBRACK | LCURLY | RCURLY | COLON | VERSION | NUM | NEWLINE | WHITE | COMMENT | STRING )

        ANTLR3_UINT32 alt6;

        alt6=11;

        switch ( LA(1) )
        {
        case '[':
        	{
        		alt6=1;
        	}
            break;
        case ']':
        	{
        		alt6=2;
        	}
            break;
        case '{':
        	{
        		alt6=3;
        	}
            break;
        case '}':
        	{
        		alt6=4;
        	}
            break;
        case ':':
        	{
        		alt6=5;
        	}
            break;
        case 'v':
        	{
        		alt6=6;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt6=7;
        	}
            break;
        case '\n':
        case '\r':
        	{
        		alt6=8;
        	}
            break;
        case '\t':
        case ' ':
        	{
        		alt6=9;
        	}
            break;
        case ';':
        	{
        		alt6=10;
        	}
            break;
        case '"':
        	{
        		alt6=11;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt6)
        {
    	case 1:
    	    // translation.g:1:10: LBRACK
    	    {
    	        /* 1:10: LBRACK */
    	        mLBRACK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // translation.g:1:17: RBRACK
    	    {
    	        /* 1:17: RBRACK */
    	        mRBRACK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // translation.g:1:24: LCURLY
    	    {
    	        /* 1:24: LCURLY */
    	        mLCURLY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // translation.g:1:31: RCURLY
    	    {
    	        /* 1:31: RCURLY */
    	        mRCURLY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // translation.g:1:38: COLON
    	    {
    	        /* 1:38: COLON */
    	        mCOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // translation.g:1:44: VERSION
    	    {
    	        /* 1:44: VERSION */
    	        mVERSION(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // translation.g:1:52: NUM
    	    {
    	        /* 1:52: NUM */
    	        mNUM(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // translation.g:1:56: NEWLINE
    	    {
    	        /* 1:56: NEWLINE */
    	        mNEWLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // translation.g:1:64: WHITE
    	    {
    	        /* 1:64: WHITE */
    	        mWHITE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // translation.g:1:70: COMMENT
    	    {
    	        /* 1:70: COMMENT */
    	        mCOMMENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // translation.g:1:78: STRING
    	    {
    	        /* 1:78: STRING */
    	        mSTRING(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
