all : SS_action.c SS_action.h SS_arglist.c SS_arglist.h SS_engine.c SS_engine.h SS_format_element.c SS_format_element.h SS_format.c SS_format.h SS_interp.c SS_interp.h SS_log.c SS_log.h SS_op_arg.c SS_op_arg.h SS_op.c SS_op.h SS_play_expr.c SS_play_expr.h SS_playlist.c SS_playlist.h SS_script_name.c SS_script_name.h SS_scriptset.c SS_scriptset.h SS_script.c SS_script.h SS_silence_def.c SS_silence_def.h SS_statement.c SS_statement.h SS_translationset.c SS_translationset.h SS_translationstring.c SS_translationstring.h SS_translation.c SS_translation.h SS_vardef.c SS_vardef.h 

clean: 
	rm SS*.[ch]

SS_action.c SS_action.h : SS_action.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_arglist.c SS_arglist.h : SS_arglist.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_engine.c SS_engine.h : SS_engine.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_format_element.c SS_format_element.h : SS_format_element.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_format.c SS_format.h : SS_format.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_interp.c SS_interp.h : SS_interp.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_log.c SS_log.h : SS_log.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_op_arg.c SS_op_arg.h : SS_op_arg.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_op.c SS_op.h : SS_op.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_play_expr.c SS_play_expr.h : SS_play_expr.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_playlist.c SS_playlist.h : SS_playlist.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_script_name.c SS_script_name.h : SS_script_name.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_scriptset.c SS_scriptset.h : SS_scriptset.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_script.c SS_script.h : SS_script.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_silence_def.c SS_silence_def.h : SS_silence_def.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_statement.c SS_statement.h : SS_statement.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_translationset.c SS_translationset.h : SS_translationset.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_translationstring.c SS_translationstring.h : SS_translationstring.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_translation.c SS_translation.h : SS_translation.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

SS_vardef.c SS_vardef.h : SS_vardef.xml apigen.gsl per_obj.gsl
	gsl apigen.gsl

